### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by sunnysideup** [AndrewHaine/silverstripe-webpack-theme#3]
Hi Andrew

We have been working with your code.  It is GREAT!

We have now created our own module:

https://github.com/sunnysideup/silverstripe-sswebpack_engine_only

What have tried to make it even more modular.  Primarily we have tried to split up webpack from the project at hand.  It is a work in progress, but we are getting there.  We end up with the following folders:

sswebpack: the webpack engine only
sswebpack_dist: the production files from sswebpack
sswebpack_base: any generic code that we take from project to project
sswebpack_mysite: any CSS / JS for the project at hand
sswebpack_node_modules: any additional node modules for the project at hand.

If you like this approach then maybe we can work together on this in one way or another.

Thank you again for the awesome inspiration!

**Comment by sunnysideup** [comment]
You may also find this module helpful: 
https://github.com/sunnysideup/silverstripe-webpack_requirements_backend

Happy to explain all of the above in writing or call.

**Comment by AndrewHaine** [comment]
Hey,
Thank you for the feedback, really appreciate it!

Will definitely take a look at your fork, I like the idea of separating out the build system from the assets etc, when I get the time i'll see about incorporating it into this module and will be in contact if I have any questions.

Closing for now but once again appreciate the feedback :)
Thanks, Andrew
